### ISSUE TITLE
Support for towny shop plots

### ISSUE THREAD

**Issue by rmarmorstein** [LlmDl/TownyTNEMobsControl#4]
iConomy Chest Shop is the only plugin which appears to have support for the towny shop plot feature.

Adding to this plugin to support the TNE shops would provide a great system to bring that functionality to a newer plugin that is being maintained.

**Comment by LlmDl** [comment]
Good idea.

**Comment by LlmDl** [comment]
Once @creatorfromhell adds in some of the events that are required for this to happen, I'll start work on it.

**Comment by LlmDl** [comment]
@Rmarmorstein if you'd like to be my beta tester you can try out this pre-release: https://cdn.discordapp.com/attachments/388338495036456960/625127922449121291/Towny-TNE-1.1.jar

You'll need all three of the latest jars of TNE from here: https://github.com/TheNewEconomy/TNE-Bukkit/packages

And you'll need this pre-release version of Towny 0.94.0.11:  https://cdn.discordapp.com/attachments/388338495036456960/625127913305538583/Towny-0.94.0.11.jar

I have gone over things fairly well already so it shouldn't present you any bugs. If you find anything just let me know here.

**Comment by LlmDl** [comment]
~~I should also disclose there's a bug in signs where when you make the sign it doesn't close the inventory screen when you click confirm amount. It'll probably be fixed soon.~~

That looks like it's been fixed in TNE 1.1.8.29.

**Comment by rmarmorstein** [comment]
[22:03:18 ERROR]: [Towny-TNE] TNE Version insufficient, go download TNE 0.1.1.8M4 or newer.
[22:03:18 INFO]: [Towny-TNE] Disabling Towny-TNE v1.1
[22:03:18 ERROR]: Error occurred while enabling Towny-TNE v1.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.gmail.llmdlio.townytne.RewardsListener@35cb6c2c while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:574) ~[paper.jar:git-Paper-194]
        at com.gmail.llmdlio.townytne.TownyTNE.registerListeners(TownyTNE.java:88) ~[?:?]
        at com.gmail.llmdlio.townytne.TownyTNE.onEnable(TownyTNE.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper.jar:git-Paper-194]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paper.jar:git-Paper-194]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paper.jar:git-Paper-194]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paper.jar:git-Paper-194]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paper.jar:git-Paper-194]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[paper.jar:git-Paper-194]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[paper.jar:git-Paper-194]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[paper.jar:git-Paper-194]
        at java.lang.Thread.run(Thread.java:834) [?:?]

I seem to be getting this error

**Comment by LlmDl** [comment]
That would be because your TNE is too old, go download the 0.1.1.9 version that was put out today:
https://www.spigotmc.org/resources/the-new-economy.7805/updates

**Comment by LlmDl** [comment]
This is out as Towny-TNE 1.1. https://www.spigotmc.org/resources/towny-tne.71240/update?update=299623
